version: '3'

services:
  web:
    container_name: web
    image: web
    build: web/
    ports:
      - "3000:3000"
  api:
    container_name: api
    image: api
    build: api/
    ports:
      - "4000:4000"